Introduce bypass_upstream_stats #292
vozlt/nginx-module-vts pull request #293
Opened 2024-01-23 16:09 UTC by u5surf

fixes: #292 

* it is able to disable intentionally statistics collection for upstream servers.

2025-01-01 10:14 UTC, SuperQ commented on README.md
> +### vhost_traffic_status_bypass_upstream_stats
I prefer positive boolean values to avoid "double negative" for default behavior.

How about:
```suggestion
### vhost_traffic_status_stats_by_upstream
```

2025-01-02 01:35 UTC, u5surf commented on README.md
> +### vhost_traffic_status_bypass_upstream_stats
@SuperQ Thanks, Fixed it

2025-01-02 08:51 UTC, SuperQ requested changes
Typo

2025-01-02 08:51 UTC, SuperQ commented on README.md
> +  * [vhost_traffic_status_stats_by__upstream](#vhost_traffic_status_stats__by_upstream)
```suggestion
  * [vhost_traffic_status_stats_by_upstream](#vhost_traffic_status_stats_by_upstream)
```

2025-01-02 08:53 UTC, SuperQ approved these changes

2025-01-02 08:58 UTC, merged